// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  biography: dynamic(() => import("./Biography")),
  content_index: dynamic(() => import("./ContentIndex")),
  experience: dynamic(() => import("./Experience")),
  hero: dynamic(() => import("./Hero")),
  image_block: dynamic(() => import("./ImageBlock")),
  rich_text: dynamic(() => import("./RichText")),
  tech_list1: dynamic(() => import("./TechList1")),
  text_block: dynamic(() => import("./TextBlock")),
};
